### ISSUE TITLE
tonal-chords example does not work

### ISSUE THREAD

**Issue by bwestergard** [danigb/tonal#15]
The example given [here](https://www.npmjs.com/package/tonal-chords) is broken.

``` bash
> Bjorns-MacBook-Pro:zeitgeber bjornwestergard$ node
> var tonal = require('tonal')
undefined
> tonal.chord('C7')
TypeError: tonal.chord is not a function
    at repl:1:7
    at REPLServer.defaultEval (repl.js:252:27)
    at bound (domain.js:287:14)
    at REPLServer.runBound [as eval] (domain.js:300:12)
    at REPLServer.<anonymous> (repl.js:417:12)
    at emitOne (events.js:82:20)
    at REPLServer.emit (events.js:169:7)
    at REPLServer.Interface._onLine (readline.js:211:10)
    at REPLServer.Interface._line (readline.js:550:8)
    at REPLServer.Interface._ttyWrite (readline.js:827:14)
```

**Comment by ajrussellaudio** [comment]
```
> var chord = require('tonal-chords')
undefined
> chord.chord('7', 'C')
[ 'C', 'E', 'G', 'Bb' ]
```
That's as close as I can get it. I like the behaviour in the documentation, but I'd like to know the wider consensus.

**Comment by danigb** [comment]
I'm going to solve this issue and others in the next 0.60.0 version I'm working in. I hope I close this issue soon.

**Comment by danigb** [comment]
Hi,

In the latest version you can:

```js
var tonal = require('tonal')
tonal.scale('C major') // => ['C', 'D', ...]
tonal.chord('Cmaj7')
```

I hope it works for you. If you are using and older version, take care of the breaking changes. Basically the functions are now namespaced, so instead of `tonal.pc` (to get the note pitch class) you should write: `tonal.note.pc`. I hope the improved documentation (http://danigb.github.io/tonal/api/) helps.

Please free to reopen this issue if that not work for you.
Regards,
Dani
