### ISSUE TITLE
diminished not harmonizing

### ISSUE THREAD

**Issue by justinjmoses** [danigb/tonal#24]
There's a bug detecting diminisheds in `harmonize`. The example from the README states:

`tonal.harmonize('P1 m3 d5', 'C') // => ['C', 'Eb', 'Gb']`

yet only `['C', 'Eb']` is yielded

**Comment by danigb** [comment]
Hi @justinjmoses,

You're completely right. The problem is that: "d5" can be interpreted as a diminished fifth or as a note "d" in 5th octave (and harmonize treats as the latter). This is why I recommend using the inverse shorthand interval notation: "5d" instead of "d5" (a recommendation I didn't follow in the README 😢 )

The correct code should be:
`tonal.harmonize('1P 3m 5d', 'C') // => ['C', 'Eb', 'Gb']`

I'll update the README. Thanks for reporting 👍 

(feel free to reopen if I miss something)

**Comment by justinjmoses** [comment]
Makes sense. Good to know the workaround thanks @danigb
