### ISSUE TITLE
problems installing current tonal-0.50.x branch

### ISSUE THREAD

**Issue by devboell** [danigb/tonal#5]
I'll just copy the terminal commands I used:

```
git clone -b tonal-0.50.x --single-branch https://github.com/danigb/tonal.git
cd tonal
npm install
npm test
```
this resulted in
```
65 passing (125ms)
  3 failing

  1) collections filter filter lists:
     TypeError: undefined is not a function
      at Array.filter (native)
      at dist/tonal.js:616:68
      at Object.filter (dist/tonal.js:616:43)
      at Context.<anonymous> (test/collections-test.js:86:26)

  2) intervals isIntervalStr test if its interval string:
     TypeError: _.isIntervalStr is not a function
      at Context.<anonymous> (test/interval-test.js:12:22)

  3) intervals isIntervalStr interval strings are recognized:
     TypeError: undefined is not a function
      at Array.map (native)
      at dist/tonal.js:603:65
      at Context.<anonymous> (test/interval-test.js:18:24)

```

then I continued with:
```
npm run packages-install
npm run packages-build
npm run packages-test
```
which gives this error:

```
module.js:339
    throw err;
    ^

Error: Cannot find module 'tonal-pitches'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
```

**Comment by danigb** [comment]
Yes, i'm mostly renaming things so it's quite unstable branch. I'll try to fix it asap.

**Comment by danigb** [comment]
Ok, currently it's not so easy to build this project. It has two __: first, code is written in ES6 style so it has to be converted to standard (old) JS. This is solved via rollup and babel. Second, because the multi-package structure, some packages depends on other packages not yet published. This is (partially) solved via lerna (but It has some bugs, so I think it will be removed in the near future).

The good news is that to perform all this steps all you have to do is `make test-ci` .... if you are in a unix-like environment. I don't know how to make it work on windows.

I've just try it and it works on my machine. Good luck!

**Comment by devboell** [comment]
yes, that did the trick! it all works now.

And your English is near perfect, so don't worry about it :-)

**Comment by danigb** [comment]
Great! I expect to simplify this process soon and add detailed instructions when ready (and for sure, you won't need it at all when packages are published).

**Comment by danigb** [comment]
Hi @devboell 

As you can notice, the 0.50.x branch was merged to master and released, so I'm closing this issue. Yo can reopen it if you need it.
Cheers.
